#DATA PROCESSING
library(rvest)
library(dplyr)
dataset<-read.csv("00 cafesales.csv")
#View dataset
View (dataset)
#1.check for special character (gsub-global substitution)
dataset$Item<-gsub("UNKNOWN","rum cake",dataset$Item)
dataset$Item<-gsub("ERROR","chicken pizza",dataset$Item)
dataset$Quantity<-gsub("ERROR","6",dataset$Quantity)
dataset$Quantity<-gsub("UNKNOWN","8",dataset$Quantity)
dataset$Price.Per.Unit<-gsub("UNKNOWN","5",dataset$Price.Per.Unit)
dataset$Price.Per.Unit<-gsub("ERROR","4",dataset$Price.Per.Unit)
dataset$Price.Per.Unit<-gsub("1.5","9",dataset$Price.Per.Unit)
dataset$Total.Spent<-gsub("UNKNOWN","6",dataset$Total.Spent)
dataset$Total.Spent<-gsub("ERROR","3",dataset$Total.Spent)
dataset$Total.Spent<-gsub("7.5","12",dataset$Total.Spent)
dataset$Total.Spent<-gsub("4.5","7",dataset$Total.Spent)
dataset$Total.Spent<-gsub("1.5","2",dataset$Total.Spent)
dataset$Payment.Method<-gsub("UNKNOWN","Credit Card",dataset$Payment.Method)
dataset$Payment.Method<-gsub("ERROR","Gpay",dataset$Payment.Method)
dataset$Location<-gsub("UNKNOWN","Takeaway",dataset$Location)
dataset$Location<-gsub("ERROR","In-Store",dataset$Location)
dataset$Transaction.Date<-gsub("ERROR","25/12/2005",dataset$Transaction.Date)
dataset$Transaction.Date<-gsub("UNKNOWN","01/1/2006",dataset$Transaction.Date)
dataset$Item[dataset$Item == ""] <- "fresh juice"
dataset$Location[dataset$Location == ""] <- "Takeaway"
dataset$Payment.Method[dataset$Payment.Method == ""] <- "Cash"
dataset$Transaction.Date[dataset$Transaction.Date == ""] <- "25/04/2022"
View(dataset)
#2.check whether all the variable are having right datatype
str(dataset)
dataset$Transaction.ID<-as.character(dataset$Transaction.ID)
dataset$Item<-as.character(dataset$Item)
dataset$Quantity<-as.numeric(dataset$Quantity)
dataset$Price.Per.Unit<-as.numeric(dataset$Price.Per.Unit)
dataset$Total.Spent<-as.character(dataset$Total.Spent)
dataset$Payment.Method<-as.character(dataset$Payment.Method)
dataset$Location<-as.character(dataset$Location)
dataset$Transaction.Date<-as.character(dataset$Transaction.Date)
#dataset$year<-as.numeric(dataset$years)
View(dataset)
str(dataset)
dataset<-dataset[c("Item","Location","Transaction.Date","Quantity","Price.Per.Unit","Transaction.ID","Total.Spent","Payment.Method")]
View(dataset)
#let's replace missing values
dataset$Quantity=ifelse(is.na(dataset$Quantity),ave(dataset$Quantity,FUN=function(x)
  mean(x,na.rm=TRUE)),dataset$Quantity)
dataset$Price.Per.Unit=ifelse(is.na(dataset$Price.Per.Unit),ave(dataset$Price.Per.Unit,FUN=function(x)
  mean(x,na.rm=TRUE)),dataset$Price.Per.Unit)
View(dataset)
dataset$Total.Spent <- dataset$Total.Spent>20
View(dataset)
str(dataset)
dataset$Total.Spent =as.factor(dataset$Total.Spent) 
str(dataset)
write.csv(dataset,"00cafe_dataset.csv")
cafe=read.csv("00cafe_dataset.csv")
View(cafe)